replicaCount: 1
image:
  repository: ghcr.io/myx12/backend
  tag: latest
  pullPolicy: IfNotPresent

FrontendImage:
  repository: ghcr.io/myx12/frontend
  tag: latest
  pullPolicy: IfNotPresent

Service:
  type: ClusterIP
  port: 5000

frontendService:
  type: ClusterIP
  port: 80