replicaCount: 1
image:
  repository: 209479264082.dkr.ecr.ap-southeast-1.amazonaws.com/backend
  tag: latest
  pullPolicy: IfNotPresent

FrontendImage:
  repository: 209479264082.dkr.ecr.ap-southeast-1.amazonaws.com/frontend
  tag: latest
  pullPolicy: IfNotPresent

Service:
  type: ClusterIP
  port: 5000

frontendService:
  type: ClusterIP
  port: 80