name: Build and Push Docker to GHCR
description: Builds Docker image, logs into GHCR, and pushes image
inputs:
  image-name:
    description: Image name (without prefix)
    required: true
  context:
    description: Path to Dockerfile and app (e.g., ./backend)
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t ${{ inputs.image-name }} ${{ inputs.context }}

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Tag Docker image for GHCR
      run: docker tag ${{ inputs.image-name }} ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ inputs.image-name }}:latest

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ inputs.image-name }}:latest