name: Backend CI with Trivy

on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: |
          docker build -t backend-app ./backend

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.16.1
        with:
          image-ref: 'backend-app'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan result
        uses: actions/upload-artifact@v4
        with:
          name: backend-trivy-report
          path: trivy-report.txt