name: Backend CI with Trivy

on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: |
          docker build -t backend:latest ./backend
      - name: Tag Docker image
        run: docker tag backend:latest 209479264082.dkr.ecr.ap-southeast-1.amazonaws.com/backend:latest

      - name: Push to Amazon ECR
        run: docker push 209479264082.dkr.ecr.ap-southeast-1.amazonaws.com/backend:latest
      

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'backend-app'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan resul
        uses: actions/upload-artifact@v4
        with:
          name: backend-trivy-report
          path: trivy-report.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 209479264082.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Push image to ECR
        run: |
          docker push 209479264082.dkr.ecr.ap-southeast-1.amazonaws.com/backend:latest