name: Backend CI with Trivy & GHCR


on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  backend-build-and-push:
    runs-on: ubuntu-latest
    env: 
      SKIP_HELM_DEPLOY:true
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build and Push Image to GHCR
        uses: ./.github/actions/build-and-push
        with:
          image-name: backend
          context: ./backend
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}
      - name: Set up Helm
        uses: azure/setup-helm@v3
      
      - name: Deploy Helm Chart to EKS
        if: ${{ env.SKIP_HELM_DEPLOY != 'true'}}
        uses: ./.github/actions/helm-deploy
        with:
          chart_path: ./helm-chart
          release_name: logistics-system
          namespace: default
          values_file: ./helm-chart/values.yaml
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'backend'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan resul
        uses: actions/upload-artifact@v4
        with:
          name: backend-trivy-report
          path: trivy-report.txt




