name: Backend CI with Trivy & GHCR

on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  backend-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-and-push
        with:
          image-name: backend
          context: ./backend

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'backend-app'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan resul
        uses: actions/upload-artifact@v4
        with:
          name: backend-trivy-report
          path: trivy-report.txt




