name: frontend CI with Trivy & GHCR

on:
  push:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  frontend-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build and Push Image to GHCR
        uses: ./.github/actions/build-and-push
        with:
          image-name: frontend
          context: ./frontend
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'frontend'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan resul
        uses: actions/upload-artifact@v4
        with:
          name: frontend-trivy-report
          path: trivy-report.txt




